cost_skill_hex = {
    "15": [
    { sname: "攻撃", hex: "01" },
    { sname: "見切り", hex: "06" },
    { sname: "超会心", hex: "07" },
    { sname: "弱点特効", hex: "08" },
    { sname: "達人芸", hex: "0C" },
    { sname: "業物", hex: "17" },
    { sname: "弾丸節約", hex: "18" },
    { sname: "通常弾・連射矢強化", hex: "30" },
    { sname: "散弾・拡散矢強化", hex: "31" },
    { sname: "貫通弾・貫通矢強化", hex: "32" },
    { sname: "装填拡張", hex: "33" },
    { sname: "速射強化", hex: "37" },
    { sname: "根性", hex: "84"},
    ],
    "12": [
    { sname: "挑戦者", hex: "02" },
    { sname: "フルチャージ", hex: "03" },
    { sname: "逆恨み", hex: "04" },
    { sname: "死中に活", hex: "05" },
    { sname: "力の解放", hex: "09" },
    { sname: "渾身", hex: "0A" },
    { sname: "匠", hex: "16" },
    { sname: "砲術", hex: "2D" },
    { sname: "幸運", hex: "54" },
    { sname: "高速変形", hex: "6B" },
    { sname: "災禍転福", hex: "74" },
    { sname: "チューンアップ", hex: "7E" },
    { sname: "連撃", hex: "83" },
    { sname: "血氣", hex: "70" },
    { sname: "狂竜症【蝕】", hex: "75" },
    { sname: "闇討ち", hex: "77" },
    { sname: "蓄積時攻撃強化", hex: "88" },
    { sname: "冰気錬成", hex: "8C" },
    { sname: "龍気変換", hex: "8D" },
    ],
    "9": [
    { sname: "会心撃【属性】", hex: "0B" },
    { sname: "剛刃研磨", hex: "19" },
    { sname: "心眼", hex: "1A" },
    { sname: "弾導強化", hex: "1B" },
    { sname: "集中", hex: "1E" },
    { sname: "強化持続", hex: "1F" },
    { sname: "攻めの守勢", hex: "25" },
    { sname: "抜刀術【技】", hex: "26" },
    { sname: "耳栓", hex: "3D" },
    { sname: "キノコ大好き", hex: "57" },
    { sname: "火事場力", hex: "5B" },
    { sname: "翔蟲使い", hex: "68" },
    { sname: "鬼火纏", hex: "6C" },
    { sname: "合気", hex: "7A" },
    { sname: "チャージマスター", hex: "7C" },
    { sname: "攻勢", hex: "7D" },
    { sname: "研磨術【鋭】", hex: "7F" },
    { sname: "刃鱗磨き", hex: "80" },
    { sname: "龍気活性", hex: "67"},
    { sname: "激昂", hex: "72"},
    { sname: "業鎧【修羅】", hex: "73"},
    { sname: "巧撃", hex: "78"},
    { sname: "弱点特効【属性】", hex: "82"},
    { sname: "状態異常確定蓄積", hex: "86"},
    { sname: "風纏", hex: "8A"},
    { sname: "粉塵纏", hex: "8B"},
    { sname: "奮闘", hex: "91" },
    { sname: "狂竜症【翔】", hex: "8F" },
    ],
    "6": [
    { sname: "毒属性強化", hex: "12" },
    { sname: "麻痺属性強化", hex: "13" },
    { sname: "睡眠属性強化", hex: "14" },
    { sname: "爆破属性強化", hex: "15" },
    { sname: "ランナー", hex: "20" },
    { sname: "体術", hex: "21" },
    { sname: "スタミナ急速回復", hex: "22" },
    { sname: "ガード性能", hex: "23" },
    { sname: "ガード強化", hex: "24" },
    { sname: "抜刀術【力】", hex: "27" },
    { sname: "納刀術", hex: "28" },
    { sname: "ＫＯ術", hex: "29" },
    { sname: "砲弾装填", hex: "2E" },
    { sname: "特殊射撃強化", hex: "2F" },
    { sname: "装填速度", hex: "34" },
    { sname: "反動軽減", hex: "35" },
    { sname: "ブレ抑制", hex: "36" },
    { sname: "早食い", hex: "3C" },
    { sname: "耐震", hex: "3F" },
    { sname: "泡沫の舞", hex: "40" },
    { sname: "回避性能", hex: "41" },
    { sname: "回避距離ＵＰ", hex: "42" },
    { sname: "破壊王", hex: "51" },
    { sname: "壁面移動", hex: "69" },
    { sname: "逆襲", hex: "6A" },
    { sname: "顕如盤石", hex: "76" },
    { sname: "霞皮の恩恵", hex: "64"},
    { sname: "鋼殻の恩恵", hex: "65"},
    { sname: "炎鱗の恩恵", hex: "66"},
    { sname: "煽衛", hex: "79"},
    { sname: "剛心", hex: "87"},
    ],
    "3": [
    { sname: "火属性攻撃強化", hex: "0D" },
    { sname: "水属性攻撃強化", hex: "0E" },
    { sname: "氷属性攻撃強化", hex: "0F" },
    { sname: "雷属性攻撃強化", hex: "10" },
    { sname: "龍属性攻撃強化", hex: "11" },
    { sname: "スタミナ奪取", hex: "2A" },
    { sname: "滑走強化", hex: "2B" },
    { sname: "笛吹き名人", hex: "2C" },
    { sname: "防御", hex: "38" },
    { sname: "精霊の加護", hex: "39" },
    { sname: "体力回復量ＵＰ", hex: "3A" },
    { sname: "回復速度", hex: "3B" },
    { sname: "風圧耐性", hex: "3E" },
    { sname: "属性やられ耐性", hex: "48" },
    { sname: "毒耐性", hex: "49" },
    { sname: "麻痺耐性", hex: "4A" },
    { sname: "睡眠耐性", hex: "4B" },
    { sname: "気絶耐性", hex: "4C" },
    { sname: "泥雪耐性", hex: "4D" },
    { sname: "爆破やられ耐性", hex: "4E" },
    { sname: "砥石使用高速化", hex: "55" },
    { sname: "アイテム使用強化", hex: "58" },
    { sname: "広域化", hex: "59" },
    { sname: "満足感", hex: "5A" },
    { sname: "不屈", hex: "5C" },
    { sname: "ひるみ軽減", hex: "5D" },
    { sname: "腹減り耐性", hex: "60" },
    { sname: "飛び込み", hex: "61" },
    { sname: "陽動", hex: "62" },
    { sname: "乗り名人", hex: "63" },
    { sname: "供応", hex: "7B" },
    { sname: "壁面移動【翔】", hex: "81" },
    ],
    "-99": [
        { sname: "鈍器使い", hex: "1C" },
        { sname: "弓溜め段階解放", hex: "1D" },
        { sname: "植生学", hex: "4F" },
        { sname: "地質学", hex: "50" },
        { sname: "捕獲名人", hex: "52" },
        { sname: "剥ぎ取り名人", hex: "53" },
        { sname: "ボマー", hex: "56" },
        { sname: "ジャンプ鉄人", hex: "5E" },
        { sname: "剥ぎ取り鉄人", hex: "5F" },
        { sname: "風紋の一致", hex: "6D" },
        { sname: "雷紋の一致", hex: "6E" },
        { sname: "風雷合一", hex: "6F" },
        { sname: "伏魔響命", hex: "71" },
    ]
}