talisman_skill = {
    "1": {skill_name_japanese: "攻撃", skill_name_chinese: "攻击", skill_name_english: "Attack Boost", rank:"A", skill_max: 7, s1_min: 1, s1_max: 3, s2_min: 0, s2_max: 2},
    "2": {skill_name_japanese: "挑戦者", skill_name_chinese: "挑战者", skill_name_english: "Agitator", rank:"A", skill_max: 5, s1_min: 1, s1_max: 4, s2_min: 0, s2_max: 3},
    "3": {skill_name_japanese: "フルチャージ", skill_name_chinese: "无伤", skill_name_english: "Peak Performance", rank:"A", skill_max: 3, s1_min: 1, s1_max: 3, s2_min: 0, s2_max: 2},
    "4": {skill_name_japanese: "逆恨み", skill_name_chinese: "怨恨", skill_name_english: "Resentment", rank:"A", skill_max: 5, s1_min: 1, s1_max: 4, s2_min: 0, s2_max: 3},
    "5": {skill_name_japanese: "死中に活", skill_name_chinese: "死里逃生", skill_name_english: "Resuscitate", rank:"A", skill_max: 3, s1_min: 1, s1_max: 3, s2_min: 0, s2_max: 2},
    "6": {skill_name_japanese: "見切り", skill_name_chinese: "看破", skill_name_english: "Critical Eye", rank:"A", skill_max: 7, s1_min: 1, s1_max: 3, s2_min: 0, s2_max: 2},
    "7": {skill_name_japanese: "超会心", skill_name_chinese: "超会心", skill_name_english: "Critical Boost", rank:"S", skill_max: 3, s1_min: 1, s1_max: 3, s2_min: 0, s2_max: 2},
    "8": {skill_name_japanese: "弱点特効", skill_name_chinese: "弱点特效", skill_name_english: "Weakness Exploit", rank:"A", skill_max: 3, s1_min: 1, s1_max: 3, s2_min: 0, s2_max: 2},
    "9": {skill_name_japanese: "力の解放", skill_name_chinese: "力量解放", skill_name_english: "Latent Power", rank:"A", skill_max: 5, s1_min: 1, s1_max: 5, s2_min: 0, s2_max: 4},
    "10": {skill_name_japanese: "渾身", skill_name_chinese: "精神抖擞", skill_name_english: "Maximum Might", rank:"A", skill_max: 3, s1_min: 1, s1_max: 3, s2_min: 0, s2_max: 2},
    "11": {skill_name_japanese: "会心撃【属性】", skill_name_chinese: "会心击【属性】", skill_name_english: "Critical Element", rank:"A", skill_max: 3, s1_min: 1, s1_max: 3, s2_min: 0, s2_max: 2},
    "12": {skill_name_japanese: "達人芸", skill_name_chinese: "达人艺", skill_name_english: "Master's Touch", rank:"S", skill_max: 3, s1_min: 1, s1_max: 3, s2_min: 0, s2_max: 2},
    "13": {skill_name_japanese: "火属性攻撃強化", skill_name_chinese: "火属性攻击强化", skill_name_english: "Fire Attack", rank:"B", skill_max: 5, s1_min: 2, s1_max: 5, s2_min: 1, s2_max: 3},
    "14": {skill_name_japanese: "水属性攻撃強化", skill_name_chinese: "水属性攻击强化", skill_name_english: "Water Attack", rank:"B", skill_max: 5, s1_min: 2, s1_max: 5, s2_min: 1, s2_max: 3},
    "15": {skill_name_japanese: "氷属性攻撃強化", skill_name_chinese: "冰属性攻击强化", skill_name_english: "Ice Attack", rank:"B", skill_max: 5, s1_min: 2, s1_max: 5, s2_min: 1, s2_max: 3},
    "16": {skill_name_japanese: "雷属性攻撃強化", skill_name_chinese: "雷属性攻击强化", skill_name_english: "Thunder Attack", rank:"B", skill_max: 5, s1_min: 2, s1_max: 5, s2_min: 1, s2_max: 3},
    "17": {skill_name_japanese: "龍属性攻撃強化", skill_name_chinese: "龙属性攻击强化", skill_name_english: "Dragon Attack", rank:"B", skill_max: 5, s1_min: 2, s1_max: 5, s2_min: 1, s2_max: 3},
    "18": {skill_name_japanese: "毒属性強化", skill_name_chinese: "毒属性强化", skill_name_english: "Poison Attack", rank:"B", skill_max: 3, s1_min: 2, s1_max: 3, s2_min: 1, s2_max: 3},
    "19": {skill_name_japanese: "麻痺属性強化", skill_name_chinese: "麻痹属性强化", skill_name_english: "Paralysis Attack", rank:"A", skill_max: 3, s1_min: 1, s1_max: 3, s2_min: 0, s2_max: 2},
    "20": {skill_name_japanese: "睡眠属性強化", skill_name_chinese: "睡眠属性强化", skill_name_english: "Sleep Attack", rank:"A", skill_max: 3, s1_min: 1, s1_max: 3, s2_min: 0, s2_max: 2},
    "21": {skill_name_japanese: "爆破属性強化", skill_name_chinese: "爆破属性强化", skill_name_english: "Blast Attack", rank:"A", skill_max: 3, s1_min: 1, s1_max: 3, s2_min: 0, s2_max: 2},
    "22": {skill_name_japanese: "匠", skill_name_chinese: "匠", skill_name_english: "Handicraft", rank:"S", skill_max: 5, s1_min: 1, s1_max: 4, s2_min: 0, s2_max: 3},
    "23": {skill_name_japanese: "業物", skill_name_chinese: "利刃", skill_name_english: "Razor Sharp", rank:"A", skill_max: 3, s1_min: 1, s1_max: 3, s2_min: 0, s2_max: 2},
    "24": {skill_name_japanese: "弾丸節約", skill_name_chinese: "弹丸节约", skill_name_english: "Spare Shot", rank:"A", skill_max: 3, s1_min: 1, s1_max: 3, s2_min: 0, s2_max: 2},
    "25": {skill_name_japanese: "剛刃研磨", skill_name_chinese: "刚刃打磨", skill_name_english: "Protective Polish", rank:"A", skill_max: 3, s1_min: 1, s1_max: 3, s2_min: 0, s2_max: 2},
    "26": {skill_name_japanese: "心眼", skill_name_chinese: "心眼", skill_name_english: "Mind's Eye", rank:"S", skill_max: 3, s1_min: 1, s1_max: 3, s2_min: 0, s2_max: 2},
    "27": {skill_name_japanese: "弾導強化", skill_name_chinese: "弹道强化", skill_name_english: "Ballistics", rank:"A", skill_max: 3, s1_min: 1, s1_max: 3, s2_min: 0, s2_max: 2},
    "28": {skill_name_japanese: "鈍器使い", skill_name_chinese: "钝器能手", skill_name_english: "Bludgeoner", rank:"B", skill_max: 3, s1_min: -1, s1_max: -1, s2_min: -1, s2_max: -1},
    "30": {skill_name_japanese: "集中", skill_name_chinese: "集中", skill_name_english: "Focus", rank:"S", skill_max: 3, s1_min: 1, s1_max: 3, s2_min: 0, s2_max: 2},
    "31": {skill_name_japanese: "強化持続", skill_name_chinese: "强化持续", skill_name_english: "Power Prolonger", rank:"A", skill_max: 3, s1_min: 1, s1_max: 3, s2_min: 0, s2_max: 2},
    "32": {skill_name_japanese: "ランナー", skill_name_chinese: "跑者", skill_name_english: "Marathon Runner", rank:"S", skill_max: 3, s1_min: 1, s1_max: 3, s2_min: 0, s2_max: 2},
    "33": {skill_name_japanese: "体術", skill_name_chinese: "体术", skill_name_english: "Constitution", rank:"C", skill_max: 5, s1_min: 2, s1_max: 5, s2_min: 1, s2_max: 4},
    "34": {skill_name_japanese: "スタミナ急速回復", skill_name_chinese: "耐力急速回复", skill_name_english: "Stamina Surge", rank:"A", skill_max: 3, s1_min: 1, s1_max: 3, s2_min: 0, s2_max: 2},
    "35": {skill_name_japanese: "ガード性能", skill_name_chinese: "防御性能", skill_name_english: "Guard", rank:"A", skill_max: 5, s1_min: 2, s1_max: 5, s2_min: 1, s2_max: 4},
    "36": {skill_name_japanese: "ガード強化", skill_name_chinese: "防御强化", skill_name_english: "Guard Up", rank:"A", skill_max: 3, s1_min: 1, s1_max: 3, s2_min: 0, s2_max: 2},
    "37": {skill_name_japanese: "攻めの守勢", skill_name_chinese: "攻击守势", skill_name_english: "Offensive Guard", rank:"S", skill_max: 3, s1_min: 1, s1_max: 3, s2_min: 0, s2_max: 2},
    "38": {skill_name_japanese: "抜刀術【技】", skill_name_chinese: "拔刀术【技】", skill_name_english: "Critical Draw", rank:"S", skill_max: 3, s1_min: 1, s1_max: 3, s2_min: 0, s2_max: 2},
    "39": {skill_name_japanese: "抜刀術【力】", skill_name_chinese: "拔刀术【力】", skill_name_english: "Punishing Draw", rank:"B", skill_max: 3, s1_min: 1, s1_max: 3, s2_min: 0, s2_max: 2},
    "40": {skill_name_japanese: "納刀術", skill_name_chinese: "纳刀术", skill_name_english: "Quick Sheathe", rank:"B", skill_max: 3, s1_min: 1, s1_max: 3, s2_min: 0, s2_max: 2},
    "41": {skill_name_japanese: "ＫＯ術", skill_name_chinese: "击晕术", skill_name_english: "Slugger", rank:"B", skill_max: 3, s1_min: 1, s1_max: 3, s2_min: 0, s2_max: 2},
    "42": {skill_name_japanese: "スタミナ奪取", skill_name_chinese: "夺取耐力", skill_name_english: "Stamina Thief", rank:"C", skill_max: 3, s1_min: 2, s1_max: 3, s2_min: 1, s2_max: 3},
    "43": {skill_name_japanese: "滑走強化", skill_name_chinese: "滑走强化", skill_name_english: "Affinity Sliding", rank:"C", skill_max: 1, s1_min: -1, s1_max: -1, s2_min: -1, s2_max: -1},
    "44": {skill_name_japanese: "笛吹き名人", skill_name_chinese: "吹笛名人", skill_name_english: "Horn Maestro", rank:"C", skill_max: 1, s1_min: -1, s1_max: -1, s2_min: -1, s2_max: -1},
    "45": {skill_name_japanese: "砲術", skill_name_chinese: "炮术", skill_name_english: "Artillery", rank:"S", skill_max: 3, s1_min: 1, s1_max: 3, s2_min: 0, s2_max: 2},
    "46": {skill_name_japanese: "砲弾装填", skill_name_chinese: "炮弹装填", skill_name_english: "Load Shells", rank:"A", skill_max: 2, s1_min: 1, s1_max: 2, s2_min: 0, s2_max: 1},
    "47": {skill_name_japanese: "特殊射撃強化", skill_name_chinese: "特殊射击强化", skill_name_english: "Special Ammo Boost", rank:"A", skill_max: 2, s1_min: 1, s1_max: 2, s2_min: 0, s2_max: 1},
    "48": {skill_name_japanese: "通常弾・連射矢強化", skill_name_chinese: "通常弹・连射箭强化", skill_name_english: "Normal/Rapid Up", rank:"A", skill_max: 3, s1_min: 1, s1_max: 3, s2_min: 0, s2_max: 2},
    "49": {skill_name_japanese: "散弾・拡散矢強化", skill_name_chinese: "贯穿弹・贯穿箭强化", skill_name_english: "Pierce Up", rank:"S", skill_max: 3, s1_min: 1, s1_max: 3, s2_min: 0, s2_max: 2},
    "50": {skill_name_japanese: "貫通弾・貫通矢強化", skill_name_chinese: "散弹・扩散箭强化", skill_name_english: "Spread Up", rank:"S", skill_max: 3, s1_min: 1, s1_max: 3, s2_min: 0, s2_max: 2},
    "51": {skill_name_japanese: "装填拡張", skill_name_chinese: "装填扩充", skill_name_english: "Ammo Up", rank:"S", skill_max: 3, s1_min: 1, s1_max: 3, s2_min: 0, s2_max: 2},
    "52": {skill_name_japanese: "装填速度", skill_name_chinese: "装填速度", skill_name_english: "Reload Speed", rank:"B", skill_max: 3, s1_min: 1, s1_max: 3, s2_min: 0, s2_max: 2},
    "53": {skill_name_japanese: "反動軽減", skill_name_chinese: "减轻后坐力", skill_name_english: "Recoil Down", rank:"B", skill_max: 3, s1_min: 1, s1_max: 3, s2_min: 0, s2_max: 2},
    "54": {skill_name_japanese: "ブレ抑制", skill_name_chinese: "抑制偏移", skill_name_english: "Steadiness", rank:"B", skill_max: 3, s1_min: 1, s1_max: 3, s2_min: 0, s2_max: 2},
    "55": {skill_name_japanese: "速射強化", skill_name_chinese: "速射强化", skill_name_english: "Rapid Fire Up", rank:"S", skill_max: 3, s1_min: 1, s1_max: 3, s2_min: 0, s2_max: 2},
    "56": {skill_name_japanese: "防御", skill_name_chinese: "防御", skill_name_english: "Defense Boost", rank:"B", skill_max: 7, s1_min: 3, s1_max: 7, s2_min: 2, s2_max: 6},
    "57": {skill_name_japanese: "精霊の加護", skill_name_chinese: "精灵加护", skill_name_english: "Divine Blessing", rank:"B", skill_max: 3, s1_min: 2, s1_max: 3, s2_min: 1, s2_max: 3},
    "58": {skill_name_japanese: "体力回復量ＵＰ", skill_name_chinese: "体力回复量提升", skill_name_english: "Recovery Up", rank:"C", skill_max: 3, s1_min: 2, s1_max: 3, s2_min: 1, s2_max: 3},
    "59": {skill_name_japanese: "回復速度", skill_name_chinese: "回复速度", skill_name_english: "Recovery Speed", rank:"C", skill_max: 3, s1_min: 2, s1_max: 3, s2_min: 1, s2_max: 3},
    "60": {skill_name_japanese: "早食い", skill_name_chinese: "快吃", skill_name_english: "Speed Eating", rank:"B", skill_max: 3, s1_min: 2, s1_max: 3, s2_min: 1, s2_max: 3},
    "61": {skill_name_japanese: "耳栓", skill_name_chinese: "耳塞", skill_name_english: "Earplugs", rank:"B", skill_max: 5, s1_min: 3, s1_max: 5, s2_min: 2, s2_max: 4},
    "62": {skill_name_japanese: "風圧耐性", skill_name_chinese: "风压耐性", skill_name_english: "Windproof", rank:"B", skill_max: 3, s1_min: 2, s1_max: 3, s2_min: 1, s2_max: 3},
    "63": {skill_name_japanese: "耐震", skill_name_chinese: "耐震", skill_name_english: "Tremor Resistance", rank:"B", skill_max: 3, s1_min: 2, s1_max: 3, s2_min: 1, s2_max: 3},
    "64": {skill_name_japanese: "泡沫の舞", skill_name_chinese: "泡沫之舞", skill_name_english: "Bubbly Dance", rank:"B", skill_max: 3, s1_min: 2, s1_max: 3, s2_min: 1, s2_max: 3},
    "65": {skill_name_japanese: "回避性能", skill_name_chinese: "回避性能", skill_name_english: "Evade Window", rank:"B", skill_max: 5, s1_min: 2, s1_max: 5, s2_min: 1, s2_max: 4},
    "66": {skill_name_japanese: "回避距離ＵＰ", skill_name_chinese: "回避距离提升", skill_name_english: "Evade Extender", rank:"B", skill_max: 3, s1_min: 0, s1_max: 3, s2_min: 0, s2_max: 2},
    "67": {skill_name_japanese: "火耐性", skill_name_chinese: "火耐性", skill_name_english: "Fire Resistance", rank:"C", skill_max: 3, s1_min: -1, s1_max: -1, s2_min: -1, s2_max: -1},
    "68": {skill_name_japanese: "水耐性", skill_name_chinese: "水耐性", skill_name_english: "Water Resistance", rank:"C", skill_max: 3, s1_min: -1, s1_max: -1, s2_min: -1, s2_max: -1},
    "69": {skill_name_japanese: "氷耐性", skill_name_chinese: "冰耐性", skill_name_english: "Ice Resistance", rank:"C", skill_max: 3, s1_min: -1, s1_max: -1, s2_min: -1, s2_max: -1},
    "70": {skill_name_japanese: "雷耐性", skill_name_chinese: "雷耐性", skill_name_english: "Thunder Resistance", rank:"C", skill_max: 3, s1_min: -1, s1_max: -1, s2_min: -1, s2_max: -1},
    "71": {skill_name_japanese: "龍耐性", skill_name_chinese: "龙耐性", skill_name_english: "Dragon Resistance", rank:"C", skill_max: 3, s1_min: -1, s1_max: -1, s2_min: -1, s2_max: -1},
    "72": {skill_name_japanese: "属性やられ耐性", skill_name_chinese: "属性异常状态的耐性", skill_name_english: "Blight Resistance", rank:"B", skill_max: 3, s1_min: -1, s1_max: -1, s2_min: -1, s2_max: -1},
    "73": {skill_name_japanese: "毒耐性", skill_name_chinese: "毒耐性", skill_name_english: "Poison Resistance", rank:"C", skill_max: 3, s1_min: -1, s1_max: -1, s2_min: -1, s2_max: -1},
    "74": {skill_name_japanese: "麻痺耐性", skill_name_chinese: "麻痹耐性", skill_name_english: "Paralysis Resistance", rank:"C", skill_max: 3, s1_min: -1, s1_max: -1, s2_min: -1, s2_max: -1},
    "75": {skill_name_japanese: "睡眠耐性", skill_name_chinese: "睡眠耐性", skill_name_english: "Sleep Resistance", rank:"C", skill_max: 3, s1_min: -1, s1_max: -1, s2_min: -1, s2_max: -1},
    "76": {skill_name_japanese: "気絶耐性", skill_name_chinese: "昏厥耐性", skill_name_english: "Stun Resistance", rank:"B", skill_max: 3, s1_min: 2, s1_max: 3, s2_min: 1, s2_max: 3},
    "77": {skill_name_japanese: "泥雪耐性", skill_name_chinese: "泥雪耐性", skill_name_english: "Muck Resistance", rank:"C", skill_max: 2, s1_min: -1, s1_max: -1, s2_min: -1, s2_max: -1},
    "78": {skill_name_japanese: "爆破やられ耐性", skill_name_chinese: "爆破异常状态的耐性", skill_name_english: "Blast Resistance", rank:"C", skill_max: 3, s1_min: -1, s1_max: -1, s2_min: -1, s2_max: -1},
    "79": {skill_name_japanese: "植生学", skill_name_chinese: "植生学", skill_name_english: "Botanist", rank:"C", skill_max: 4, s1_min: -1, s1_max: -1, s2_min: -1, s2_max: -1},
    "80": {skill_name_japanese: "地質学", skill_name_chinese: "地质学", skill_name_english: "Geologist", rank:"C", skill_max: 3, s1_min: -1, s1_max: -1, s2_min: -1, s2_max: -1},
    "81": {skill_name_japanese: "破壊王", skill_name_chinese: "破坏王", skill_name_english: "Partbreaker", rank:"B", skill_max: 3, s1_min: 1, s1_max: 3, s2_min: 0, s2_max: 2},
    "84": {skill_name_japanese: "幸運", skill_name_chinese: "幸运", skill_name_english: "Good Luck", rank:"S", skill_max: 3, s1_min: 1, s1_max: 3, s2_min: 0, s2_max: 2},
    "85": {skill_name_japanese: "砥石使用高速化", skill_name_chinese: "砥石使用高速化", skill_name_english: "Speed Sharpening", rank:"B", skill_max: 3, s1_min: 2, s1_max: 3, s2_min: 1, s2_max: 2},
    "86": {skill_name_japanese: "ボマー", skill_name_chinese: "炸弹客", skill_name_english: "Bombardier", rank:"C", skill_max: 3, s1_min: -1, s1_max: -1, s2_min: -1, s2_max: -1},
    "87": {skill_name_japanese: "キノコ大好き", skill_name_chinese: "最爱蘑菇", skill_name_english: "Mushroomancer", rank:"S", skill_max: 3, s1_min: 1, s1_max: 3, s2_min: 0, s2_max: 2},
    "88": {skill_name_japanese: "アイテム使用強化", skill_name_chinese: "道具使用强化", skill_name_english: "Item Prolonger", rank:"C", skill_max: 3, s1_min: 2, s1_max: 3, s2_min: 1, s2_max: 3},
    "89": {skill_name_japanese: "広域化", skill_name_chinese: "广域化", skill_name_english: "Wide-Range", rank:"B", skill_max: 5, s1_min: 3, s1_max: 5, s2_min: 2, s2_max: 4},
    "90": {skill_name_japanese: "満足感", skill_name_chinese: "满足感", skill_name_english: "Free Meal", rank:"C", skill_max: 3, s1_min: 2, s1_max: 3, s2_min: 1, s2_max: 3},
    "91": {skill_name_japanese: "火事場力", skill_name_chinese: "火场怪力", skill_name_english: "Heroics", rank:"A", skill_max: 5, s1_min: 1, s1_max: 4, s2_min: 0, s2_max: 3},
    "92": {skill_name_japanese: "不屈", skill_name_chinese: "不屈", skill_name_english: "Fortify", rank:"C", skill_max: 1, s1_min: -1, s1_max: -1, s2_min: -1, s2_max: -1},
    "93": {skill_name_japanese: "ひるみ軽減", skill_name_chinese: "减轻胆怯", skill_name_english: "Flinch Free", rank:"B", skill_max: 3, s1_min: 2, s1_max: 3, s2_min: 1, s2_max: 3},
    "94": {skill_name_japanese: "ジャンプ鉄人", skill_name_chinese: "跳跃铁人", skill_name_english: "Flinch Free", rank:"S", skill_max: 1, s1_min: -1, s1_max: -1, s2_min: -1, s2_max: -1},
    "95": {skill_name_japanese: "剥ぎ取り鉄人", skill_name_chinese: "剥取铁人", skill_name_english: "Jump Master", rank:"C", skill_max: 1, s1_min: -1, s1_max: -1, s2_min: -1, s2_max: -1},
    "96": {skill_name_japanese: "腹減り耐性", skill_name_chinese: "饥饿耐性", skill_name_english: "Hunger Resistance", rank:"C", skill_max: 3, s1_min: 2, s1_max: 3, s2_min: 1, s2_max: 3},
    "97": {skill_name_japanese: "飛び込み", skill_name_chinese: "飞身跃入", skill_name_english: "Leap of Faith", rank:"C", skill_max: 1, s1_min: -1, s1_max: -1, s2_min: -1, s2_max: -1},
    "98": {skill_name_japanese: "陽動", skill_name_chinese: "佯动", skill_name_english: "Diversion", rank:"C", skill_max: 1, s1_min: -1, s1_max: -1, s2_min: -1, s2_max: -1},
    "99": {skill_name_japanese: "乗り名人", skill_name_chinese: "骑乘名人", skill_name_english: "Master Mounter", rank:"C", skill_max: 1, s1_min: -1, s1_max: -1, s2_min: -1, s2_max: -1},
    "104": {skill_name_japanese: "翔蟲使い", skill_name_chinese: "翔虫使", skill_name_english: "Wirebug Whisperer", rank:"C", skill_max: 3, s1_min: 2, s1_max: 3, s2_min: 1, s2_max: 3},
    "105": {skill_name_japanese: "壁面移動", skill_name_chinese: "墙面移动", skill_name_english: "Wall Runner", rank:"C", skill_max: 3, s1_min: 2, s1_max: 3, s2_min: 1, s2_max: 3},
    "106": {skill_name_japanese: "逆襲", skill_name_chinese: "逆袭", skill_name_english: "Counterstrike", rank:"B", skill_max: 3, s1_min: 1, s1_max: 3, s2_min: 0, s2_max: 2},
    "107": {skill_name_japanese: "高速変形", skill_name_chinese: "高速变形", skill_name_english: "Rapid Morph", rank:"B", skill_max: 3, s1_min: 1, s1_max: 3, s2_min: 0, s2_max: 2},
    "108": {skill_name_japanese: "鬼火纏", skill_name_chinese: "鬼火缠", skill_name_english: "Hellfire Cloak", rank:"A", skill_max: 4, s1_min: 1, s1_max: 4, s2_min: 0, s2_max: 3},
    "116": {skill_name_japanese: "災禍転福", skill_name_chinese: "因祸得福", skill_name_english: "Coalescence", rank:"A", skill_max: 3, s1_min: 1, s1_max: 3, s2_min: 0, s2_max: 2},
    "122": {skill_name_japanese: "合気", skill_name_chinese: "合气", skill_name_english: "Redirection", rank:"B", skill_max: 2, s1_min: -1, s1_max: -1, s2_min: -1, s2_max: -1},
    "123": {skill_name_japanese: "供応", skill_name_chinese: "提供", skill_name_english: "Spiribird's Call", rank:"C", skill_max: 1, s1_min: -1, s1_max: -1, s2_min: -1, s2_max: -1},
    "124": {skill_name_japanese: "チャージマスター", skill_name_chinese: "蓄力大师", skill_name_english: "Charge Master", rank:"A", skill_max: 3, s1_min: 1, s1_max: 3, s2_min: 0, s2_max: 2},
    "125": {skill_name_japanese: "攻勢", skill_name_chinese: "攻势", skill_name_english: "Foray", rank:"A", skill_max: 3, s1_min: 1, s1_max: 3, s2_min: 0, s2_max: 2},
    "126": {skill_name_japanese: "チューンアップ", skill_name_chinese: "零件改造", skill_name_english: "Tune-Up", rank:"A", skill_max: 2, s1_min: 1, s1_max: 2, s2_min: 0, s2_max: 1},
    "127": {skill_name_japanese: "研磨術【鋭】", skill_name_chinese: "打磨术【锐】", skill_name_english: "Grinder (S)", rank:"A", skill_max: 3, s1_min: 1, s1_max: 3, s2_min: 0, s2_max: 2},
    "128": {skill_name_japanese: "刃鱗磨き", skill_name_chinese: "刃鳞打磨", skill_name_english: "Bladescale Hone", rank:"A", skill_max: 3, s1_min: 1, s1_max: 3, s2_min: 0, s2_max: 2},
    "129": {skill_name_japanese: "壁面移動【翔】", skill_name_chinese: "走壁移动【翔】", skill_name_english: "Wall Runner (Boost)", rank:"C", skill_max: 1, s1_min: -1, s1_max: -1, s2_min: -1, s2_max: -1},
    "131": {skill_name_japanese: "連撃", skill_name_chinese: "连击", skill_name_english: "Burst", rank:"A", skill_max: 3, s1_min: 1, s1_max: 3, s2_min: 0, s2_max: 2},
    "100": {skill_name_japanese: "霞皮の恩恵", skill_name_chinese: "霞皮的恩惠", skill_name_english: "Chameleos Blessing", rank:"C", skill_max: 4, s1_min: 1, s1_max: 4, s2_min: 0, s2_max: 3},
    "101": {skill_name_japanese: "鋼殻の恩恵", skill_name_chinese: "钢壳的恩惠", skill_name_english: "Kushala Blessing", rank:"C", skill_max: 4, s1_min: 1, s1_max: 4, s2_min: 0, s2_max: 3},
    "102": {skill_name_japanese: "炎鱗の恩恵", skill_name_chinese: "炎鳞的恩惠", skill_name_english: "Teostra Blessing", rank:"C", skill_max: 4, s1_min: 1, s1_max: 4, s2_min: 0, s2_max: 3},
    "103": {skill_name_japanese: "龍気活性", skill_name_chinese: "龙气活性", skill_name_english: "Dragonheart", rank:"B", skill_max: 5, s1_min: 1, s1_max: 4, s2_min: 0, s2_max: 3},
    "112": {skill_name_japanese: "血氣", skill_name_chinese: "气血", skill_name_english: "Blood Rite", rank:"B", skill_max: 3, s1_min: 0, s1_max: 3, s2_min: 0, s2_max: 2},
    "117": {skill_name_japanese: "狂竜症【蝕】", skill_name_chinese: "狂龙症【蚀】", skill_name_english: "Bloodlust", rank:"A", skill_max: 3, s1_min: 0, s1_max: 3, s2_min: 0, s2_max: 2},
    "113": {skill_name_japanese: "伏魔響命", skill_name_chinese: "伏魔耗命", skill_name_english: "Dereliction", rank:"S", skill_max: 3, s1_min: 0, s1_max: 2, s2_min: 0, s2_max: 1},
    "114": {skill_name_japanese: "激昂", skill_name_chinese: "激昂", skill_name_english: "Furious", rank:"B", skill_max: 3, s1_min: 0, s1_max: 3, s2_min: 0, s2_max: 2},
    "115": {skill_name_japanese: "業鎧【修羅】", skill_name_chinese: "业铠【修罗】", skill_name_english: "Mail of Hellfire", rank:"B", skill_max: 3, s1_min: 0, s1_max: 3, s2_min: 0, s2_max: 2},
    "119": {skill_name_japanese: "闇討ち", skill_name_chinese: "偷袭", skill_name_english: "Sneak Attack", rank:"A", skill_max: 3, s1_min: 0, s1_max: 3, s2_min: 0, s2_max: 2},
    "120": {skill_name_japanese: "巧撃", skill_name_chinese: "巧击", skill_name_english: "Adrenaline Rush", rank:"A", skill_max: 3, s1_min: 0, s1_max: 3, s2_min: 0, s2_max: 2},
    "130": {skill_name_japanese: "弱点特効【属性】", skill_name_chinese: "弱点特效【属性】", skill_name_english: "Element Exploit", rank:"A", skill_max: 3, s1_min: 0, s1_max: 3, s2_min: 0, s2_max: 2},
    "134": {skill_name_japanese: "状態異常確定蓄積", skill_name_chinese: "状态异常必定累积", skill_name_english: "Status Trigger", rank:"B", skill_max: 3, s1_min: 0, s1_max: 3, s2_min: 0, s2_max: 2},
    "118": {skill_name_japanese: "顕如盤石", skill_name_chinese: "坚如磐石", skill_name_english: "Defiance", rank:"C", skill_max: 5, s1_min: 1, s1_max: 5, s2_min: 0, s2_max: 4},
    "132": {skill_name_japanese: "根性", skill_name_chinese: "毅力", skill_name_english: "Guts", rank:"S", skill_max: 3, s1_min: 0, s1_max: 2, s2_min: 0, s2_max: 1},
    "121": {skill_name_japanese: "煽衛", skill_name_chinese: "嘲讽防御", skill_name_english: "Embolden", rank:"C", skill_max: 3, s1_min: 0, s1_max: 3, s2_min: 0, s2_max: 2},
    "135": {skill_name_japanese: "剛心", skill_name_chinese: "刚心", skill_name_english: "Intrepid Heart", rank:"C", skill_max: 2, s1_min: 0, s1_max: 2, s2_min: 0, s2_max: 1},
    "136": {skill_name_japanese: "蓄積時攻撃強化", skill_name_chinese: "累积时攻击强化", skill_name_english: "Buildup Boost", rank:"A", skill_max: 3, s1_min: 0, s1_max: 3, s2_min: 0, s2_max: 2},
    "137": {skill_name_japanese: "狂化", skill_name_chinese: "狂化", skill_name_english: "Berserk", rank:"S", skill_max: 2, s1_min: 0, s1_max: 2, s2_min: 0, s2_max: 1},
    "145": {skill_name_japanese: "奮闘", skill_name_chinese: "奋斗", skill_name_english: "Strife", rank:"A", skill_max: 3, s1_min: 0, s1_max: 3, s2_min: 0, s2_max: 2},
    "138": {skill_name_japanese: "風纏", skill_name_chinese: "风绕", skill_name_english: "Wind Mantle", rank:"A", skill_max: 3, s1_min: 0, s1_max: 3, s2_min: 0, s2_max: 2},
    "139": {skill_name_japanese: "粉塵纏", skill_name_chinese: "粉尘绕", skill_name_english: "Powder Mantle", rank:"A", skill_max: 3, s1_min: 0, s1_max: 3, s2_min: 0, s2_max: 2},
    "140": {skill_name_japanese: "冰気錬成", skill_name_chinese: "寒气炼成", skill_name_english: "Frostcraft", rank:"A", skill_max: 3, s1_min: 0, s1_max: 3, s2_min: 0, s2_max: 2},
    "141": {skill_name_japanese: "龍気変換", skill_name_chinese: "龙气转换", skill_name_english: "Dragon Conversion", rank: "A", skill_max: 3, s1_min: 0, s1_max: 3, s2_min: 0, s2_max: 2 },
    "143": {skill_name_japanese: "狂竜症【翔】", skill_name_chinese: "狂龙症【翔】", skill_name_english: "Frenzied Bloodlust", rank:"A", skill_max: 3, s1_min: 0, s1_max: 3, s2_min: 0, s2_max: 2},
}